### ISSUE TITLE
Add request logging to Helium

### ISSUE THREAD

**Issue by bartr** [bartr/bluebell#14]
Should we add basic request logging (console.writeline) to the Helium app?

This would let you debug issues by looking at the log files in Kudu. It duplicates Azure Monitor a little but seems simpler to debug and provides instant results vs. the delayed results of Azure Monitor. This would also allow Prometheus to pickup the results.

Suggested line format (tab delimited):
instanceId   httpResultCode   totalMs   path

The logger will add date time automatically.

Should we only log 4xx and 5xx requests or all requests?

We could add additional fields like the standard web loggers, but that's already in Azure Monitor and the goal is simplicity.

We will need this for the AKS version of Helium so that prometheus can pick up the logs. Need to make sure whatever we do works with prometheus.

**Comment by aflinchb** [comment]
For simplicity, only logging 4xx and 5xx makes sense, especially if the goal is to quickly view what went wrong. It would be easy to fork+code/expand and add successful requests.  However, if the main features of Prometheus really need the full request data to be useful (I am not very familiar, but saw alerting) I see the benefit of adding in successful requests.

**Comment by bartr** [comment]
I talked to Eddie about this today and we need this for the AKS version, so I'm going to add here. I'll make it configurable so you can log 2xx, 3xx, 4xx and/or 5xx results as a simple tab delimited output. Since Prometheus will add date time / pod stamps, I won't write the date stamp.

**Comment by bartr** [comment]
Resolved with PR #28
