### ISSUE TITLE
Add CI-CD instructions for Github Actions

### ISSUE THREAD

**Issue by bartr** [bartr/bluebell#57]

**Comment by aflinchb** [comment]
Investigated this -- I tested it out using a github workflow/action yml file to build and push to ACR (yml copied below).

I will clean up and expand on the steps in an actual md file, but I forgot which repo we decided to put the yml file(s) for ci/cd.  I think it was RetailDevCrew/helium.

General steps:
1. Update yml file below with the correct ACR name (i.e. replace "helium" with $He_Name from readme steps.
2. Create a service principal with acrpush permissions to the acr
3. In the github repo settings, add the following secrets:
- **secret name**: REGISTRY_USERNAME ; **value**: service principal id 
- **secret name**: REGISTRY_PASSWORD ; **value**: service principal password 
4.  Move the cicdAction.yml file to .github/workflows/ directory.
5.  Push changes to master to see workflow executed.  (Note: the yml below sets the trigger as pushes on the master branch, this can be updated)



**cicdAction.yml**:
name: CI-ACR

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and publish to ACR
      uses: azure/docker-login@v1
      with:
        login-server: helium.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}    
    - run: |
        docker build -t helium.azurecr.io/helium-csharp:latest --target=release .
        docker tag helium.azurecr.io/helium-csharp:latest helium.azurecr.io/helium-csharp:${{ github.sha }}
        docker push helium.azurecr.io/helium-csharp:${{ github.sha }}
        docker push helium.azurecr.io/helium-csharp:latest

**Comment by aflinchb** [comment]
Docs here: https://github.com/RetailDevCrews/helium/pull/4
