### ISSUE TITLE
Write developer documentation

### ISSUE THREAD

**Issue by bartr** [bartr/bluebell#93]
The readme focuses on how to build and deploy the apps. Write language specific docs that focus on the key parts of the code and how they work.

**Comment by aflinchb** [comment]
@bartr -- I made a branch in retaildevcrew/helium-csharp (and an initial .md file: https://github.com/RetailDevCrews/helium-csharp/blob/devdoc/DEVELOPER.md) to collaborate in.  I started an outline that highlight some of the key parts.  Let me know if you'd prefer to break out into different files, remove sections, add sections, etc.

**Comment by bartr** [comment]
Resolved (for C#) in PR #98 Dev Docs
